// One machine-readable record for tests and invariant checks. No production host data is read.
import {spawnSync,execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {mkdirSync,readFileSync,writeFileSync,existsSync,rmSync} from 'node:fs';
import {resolve,join} from 'node:path';
if(Number(process.versions.node.split('.')[0])<24) throw new Error('Trust validation requires Node 24 or later');
const publishSummary=process.argv.includes('--publish-summary');
const testsOnly=process.argv.includes('--tests-only'),checksOnly=process.argv.includes('--checks-only');
if(publishSummary&&(testsOnly||checksOnly))throw new Error('Summary requires full validation');
if(testsOnly&&checksOnly)throw new Error('Choose tests-only or checks-only');
const out=resolve('artifacts/trust-validation');mkdirSync(out,{recursive:true});
const testJson=join(out,'tests.json');if(!checksOnly)rmSync(testJson,{force:true});
const files=execFileSync('git',['ls-files','--cached','--others','--exclude-standard','--','src','tests','scripts','package.json','package-lock.json','tsconfig.json','vitest.config.ts'],{encoding:'utf8'}).trim().split('\n').filter(Boolean).sort();
const digest=createHash('sha256');for(const file of [...new Set(files)])digest.update(file+'\0').update(readFileSync(file)).update('\0');
const steps=[];
function run(name,command,args){
 const start=Date.now(),result=spawnSync(command,args,{encoding:'utf8',maxBuffer:20*1024*1024});
 writeFileSync(join(out,name+'.log'),(result.stdout??'')+(result.stderr??'')+(result.error?.message??''));
 steps.push({name,status:result.status===0?'passed':'failed',exitCode:result.status,signal:result.signal,elapsedMs:Date.now()-start});
}
if(!checksOnly)run('tests','npm',['test','--','--reporter=json','--outputFile='+testJson]);
if(!testsOnly){
 if(checksOnly)run('build','npm',['run','build']);
 if(steps.every(step=>step.status==='passed'))for(const script of ['verify-target-architecture','verify-research-pilot','verify-multi-case-research','run-recall-baseline'])run(script,process.execPath,['scripts/'+script+'.mjs']);
}
const testResult=!checksOnly&&existsSync(testJson)?JSON.parse(readFileSync(testJson,'utf8')):null;
const report={schemaVersion:1,generatedAt:new Date().toISOString(),node:process.version,gitHead:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),sourceFingerprint:digest.digest('hex'),
 status:steps.length&&steps.every(step=>step.status==='passed')?'passed':'failed',
 tests:testResult?{files:testResult.testResults.length,total:testResult.numTotalTests,passed:testResult.numPassedTests,failed:testResult.numFailedTests,pending:testResult.numPendingTests}:null,steps,
 scope:{host:'local stdio process crash/restart with synthetic data; no production host rollout',migration:'v1-v17 fixtures; v12 explicitly reconstructed; current fresh-install parity and fault recovery',modelUse:'not_measured'}};
writeFileSync(join(out,testsOnly?'tests-report.json':checksOnly?'checks-report.json':'report.json'),JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify(report,null,2));
if(report.status!=='passed')process.exitCode=1;

if(publishSummary&&report.status==='passed') {
 const summary=`# Trust hardening validation\n\nGenerated by \`npm run verify:trust -- --publish-summary\` on ${report.generatedAt}. This is the current five-PR validation record; earlier release reports are historical snapshots.\n\n- Runtime: ${report.node}.\n- Tests: ${report.tests.files} files, ${report.tests.passed}/${report.tests.total} passed, ${report.tests.failed} failed, ${report.tests.pending} pending.\n- Checks: ${report.steps.filter(step=>step.name!=='tests').map(step=>step.name+': '+step.status).join('; ')}.\n- Observed HEAD before validation: \`${report.gitHead}\`. Uncommitted source is included in the fingerprint below.\n- Validated source fingerprint: \`${report.sourceFingerprint}\` (SHA-256 over the sorted source/test/script/config files listed by the generator).\n\nThe v1–v17 migration matrix checks rollback, repeat migration, schema parity, FTS and preserved record links. v12 is explicitly reconstructed from v13's source with the v13 migration disabled; it is not an independently released fixture. Schema v18 repairs legacy queue nullability.\n\nReal local process tests kill and restart the stdio server, kill an Outbox worker on its final attempt, and kill migration before the version commit. Synthetic data is used throughout. Native host rollout and actual model use are not measured.\n\nMachine-readable results and per-step logs are generated under \`artifacts/trust-validation/\` (ignored by Git). CI prints equivalent test/check reports from its separate jobs.\n`;
 writeFileSync(resolve('docs/implementation/trust-validation.md'),summary);
}
